### ISSUE TITLE
Pipe break while using tsMuxeR

### ISSUE THREAD

**Issue by Sami32** [DigitalMediaServer/DigitalMediaServer#118]
>DEBUG 2018-11-02 16:25:52.718 [Thread-311] IPC pipe interrupted after writing 0 bytes, shutting down...
TRACE 2018-11-02 16:25:52.718 [Thread-311] 
java.io.InterruptedIOException: null
	at java.io.PipedInputStream.awaitSpace(PipedInputStream.java:275)
	at java.io.PipedInputStream.receive(PipedInputStream.java:231)
	at java.io.PipedOutputStream.write(PipedOutputStream.java:149)
	at net.pms.io.PipeIPCProcess.run(PipeIPCProcess.java:81)

**Comment by Nadahar** [comment]
This isn't really a problem, it just means that the pipe thread has been interrupted (which is the "normal" way for other threads to tell a thread to stop). This seems to be caused by `InterruptedIOException` so I guess that the pipe was closed or something like that.

These exceptions usually don't have a description message (because they're not really errors, but inter-thread signals). which is why the description is simply `null`.

Ideally these shouldn't happen, but until the pipe handling has been refactored so that things are shut down in proper order, we will see things like this. This exception does *not* indicate a "broken pipe".
