### ISSUE TITLE
Remove PID code and ffmpeg.webfilter, WEB.conf and /var/log/ logging

### ISSUE THREAD

**Issue by Sami32** [DigitalMediaServer/DigitalMediaServer#75]
Unecessary code that crowd the log for nothing.

**Comment by Nadahar** [comment]
Looks like a good idea :+1:  The PID removal is already covered by #73.

**Comment by Sami32** [comment]
I mean that log that the user is not root so cannot access them and that user folder will be used instead is of no use IMO, only potentially confusing for the log readers.

**Comment by Nadahar** [comment]
I've actually been meaning to change the default log level to `info`. The debug information is just that - debug information, and it can be useful for us to see what has been tried and why. Using `debug` as the default is a quasi solution by UMS because they didn't always think `info` provided enough information AFAIK. Instead of changing whatever logging deemed necessary to `info`, the "easy" solution was to change the default.

That said, it looks like most of this logging is `trace`. Maybe we can just do some tweaks to the log level. I think it's very useful to be able to see how the folders have been resolved when debugging.

**Comment by Nadahar** [comment]
> I mean that log that the user is not root so cannot access them and that user folder will be used instead is of no use IMO, only potentially confusing for the log readers.

Remember that this setup is just the default. It's very possible to change these default permissions so that the user have access to write to `/var/log` for example.

**Comment by Sami32** [comment]
just meant that if you are not running dms as root you dont have any use of that log message telling you that you are not

**Comment by Sami32** [comment]
Yes, your default logger setting change seem to be the best approach.

**Comment by Nadahar** [comment]
When looking closer at this I don't quite understand. `WEB.conf` is already empty; everything is commented out. It's only there as a template to give the users an idea of how to use it if they want to. Until we have a better replacement, I think it should just stay..?

Regarding `ffmpeg.webfilter` I can't see that we have that file at all.

**Comment by Sami32** [comment]
Yes, i've done a file for a user around 2 years ago now, but it can only be used for images as it is now, as it rely on Jumpy and one other plugin to resolve the addresses!
So after you, but for now we should remove it or only leave some pictures links.

And since `ffmpeg.webfilter` is only used for these plugins you can remove it if you want to.

**Comment by Sami32** [comment]
It is only workaround and hack that should have been properly fixed using FFmpeg IMO.
But i don't want look at that now and get distracted.
FFmpeg and VLC can handle such protocols and analyse such online streams.

**Comment by Nadahar** [comment]
@Sami32 The point is that I can't find `ffmpeg.webfilter`. I think that file is already removed. When it comes to `WEB.conf`, there are currently no links in it.

**Comment by Sami32** [comment]
Then i'll remove the webfilter file and you just need to remove such logging saying it doesn't find the files ;)

If all is commented there is a reason ;)
But if you like you can uncomment the images links.

**Comment by Sami32** [comment]
In external-resources folder

**Comment by Sami32** [comment]
As you like

**Comment by Sami32** [comment]
But if they want browse their own photo from DMS they could appreciate some example but it could be only my view.

**Comment by Nadahar** [comment]
You're right. I don't understand how I didn't find it... I blame Eclipse :innocent:

**Comment by Nadahar** [comment]
> But if they want browse their own photo from DMS they could appreciate some example but it could be only my view.

It depends on what is installed with the OS, but with Windows for example there are some example photos installed. Those should be part of the default folders.

Most users will never figure out how to edit the WEB.conf file, which is why I think it's a bad idea that they have to edit it to get rid of those useless resources.

**Comment by Sami32** [comment]
The Internet links doesn't depend on the OS.

**Comment by Nadahar** [comment]
Most users will never edit DMS.conf. They will use the GUI to configure. That's my very point with `WEB.conf`, as long as it can't be edited from the GUI, most users won't know how to remove those irrelevant entries.

**Comment by Sami32** [comment]
No need, no entries are uncommented, isn't it?

**Comment by Nadahar** [comment]
@Sami32 All entries as commented, I meant *if* we uncommented some of them.

**Comment by Sami32** [comment]
Feel i you like. If you want uncomment just take care of only doing that with images links.
